main/main/urls.py
from django.contrib import admin
from django.urls import path, include

from sellers.views import Index

from django.conf import settings
from django.conf.urls.static import static
from staff.views import *

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', Index.as_view(), name='index'),        # opening page
    path('sellers/', include('sellers.urls')),
    path('admn/', include('staff.urls')),
    path('product/', include('product.urls')),

    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/staff/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    # for staff only
    path('addcloth/', AddCloth.as_view(), name = 'add'),
    path('updatecloth/<int:pid>', UpdateCloth.as_view(), name= 'update'),

    path('', AdminLogIn.as_view(), name='admn'),
    path('admnlogout/', AdminLogOut.as_view(), name='admLO'),
    path('dash/', AdmView.as_view(), name= 'dash'),
    path('users/', AdmUsrView.as_view(), name= 'admU'),
    path('products/', AdmProView.as_view(), name= 'admP'),
    path('messages/', AdmMsgView.as_view(), name= 'admM'),
    path('feedbacks/', AdmFeedView.as_view(), name= 'admF'),
    # Admin Operations
    path('deleteMessage/<int:id>', admDeleteMessage, name='dltmsg'),
    path('feededit/<int:id>', AdmFeedEdit.as_view(), name='admfeededit'),
    path('feeddelete/<int:id>', admFeedDelete, name='admdltfeed'),
    path('deleteReport/<int:id>', admDeleteReport, name='d_reports'),
    path('createStaff/', CreateStaff.as_view(), name="cstaff"),
    path('makeStaff/<int:id>', makeStaff, name='mstaff'),
    path('deleteStaff/<int:id>', deleteStaff, name='dstaff'),
    path('activateUser/<int:id>', activateUser, name="activate"),
    path('deactivateUser/<int:id>', deactivateUser, name="deactivate"),
]

main/sellers/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime
from django.contrib.auth.models import User
from product.models import ClothModel
# Create your models here.

 
class MessageModel(models.Model):
    email = models.EmailField()
    message = models.TextField(max_length=500)
    datetime = models.DateTimeField(default=timezone.now())

class FeedbackModel(models.Model):
    pro = models.ForeignKey(ClothModel, on_delete=models.CASCADE)
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, default='')
    feedback = models.TextField(max_length=500)
    likes = models.ManyToManyField(User, related_name="feed_likes", blank=True,null=True)
    datetime = models.DateTimeField(default=datetime.now().strftime("%Y%m%d %H:%M:%S"))

class Report(models.Model):
    feedback = models.ForeignKey(FeedbackModel, on_delete=models.CASCADE)
    user = models.IntegerField()
    report  = models.CharField(max_length=100)
    datetime = models.DateTimeField(default=datetime.now())

main/staff/models.py
from django.db import models
from datetime import datetime
from sellers.models import MessageModel, FeedbackModel
# Create your models here.

main/staff/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
# class StaffCreationForm(forms.ModelForm):
#     class Meta:
#         model = User
#         fields = ['first_name', 'last_name', 'username', 'password']
#         def fun(self):
#             self.is_staff=True

main/staff/views.py
from typing import Any
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import View, TemplateView, CreateView, DeleteView, FormView, ListView, UpdateView
from django.contrib import messages
from product.models import *
from sellers.models import *
from product.forms import *
from sellers.forms import FeedbackForm
from django.utils.decorators import method_decorator
from sellers.views import signin_required

# Create your views here.

def staffonly(fun):
    def inner(request, *args, **kwargs):
        if request.user.is_staff:
            return fun(request, *args, **kwargs)
        else:
            messages.error(request, "U are not a Staff")
            return redirect("index")
    return inner

# Only for Staff 
@method_decorator(staffonly, name="dispatch")
class AddCloth(View):
    def get(self, request, *args, **kwargs):
        form = ClothForm()
        return render(request, "addcloth.html", {"form":form})
    def post(self, request, *args, **kwargs):
        form_data = ClothForm(data= request.POST, files= request.FILES)
        if form_data.is_valid():
            form_data.save()
            messages.success(request, "Added")
            form = ClothForm()
            # return render(request, "addcloth.html", {"form":form})
            return redirect('index')
        else:
            messages.warning(request, "Something went error")
            return render(request, "addcloth.html", {"form":form_data})
        
@method_decorator(staffonly, name="dispatch")      
class UpdateCloth(View):
    def get(self, request, *args, **kwargs):
        id = kwargs.get('pid')
        pro = ClothModel.objects.get(id = id)
        form = ClothForm(instance=pro)
        return render(request, "updatecloth.html", {'form':form})
    def post(self, request, *args, **kwargs):
        id = kwargs.get('pid')
        pro = ClothModel.objects.get(id = id)
        form_data = ClothForm(data=request.POST, files=request.FILES, instance=pro)   
        if form_data.is_valid():
            if 'update' in request.POST:
                form_data.save()
                form = ClothForm()
                messages.success(request, "Cloth Updated")
                # return render(request, "updatecloth.html", {'form':form})
                return redirect('index')
            elif 'delete' in request.POST:
                pro.delete()
                form = ClothForm()
                messages.info(request, "Cloth Deleted")
                # return render(request, "updatecloth.html", {'form':form}) 
                return redirect('index')        
        else:
            return render(request, "updatecloth.html", {'form':form_data})    



def adminOnly(fun):
    def inner(request, *args, **kwargs):
        if request.user.is_superuser:
            return fun(request, *args, **kwargs)
        else:
            messages.error(request, "U are a Fraud")
            return redirect("admn")
    return inner
# Admin Login
from sellers.forms import SellerLogInForm
from django.contrib.auth import authenticate, login, logout
class AdminLogIn(View):
    def get(self, request, *args, **kwargs):
        form = SellerLogInForm()
        return render(request, "admin_login.html", {'form':form})
    def post(self, request, *args, **kwargs):
        form_data = SellerLogInForm(data=request.POST)
        if form_data.is_valid():
            uname = form_data.cleaned_data.get('username')
            psw = form_data.cleaned_data.get('password')
            user = authenticate(request, username=uname, password=psw)
            if user.is_superuser == True:
                login(request, user)
                messages.success(request, 'Login succesfull')
                return redirect('dash')
            else:
                messages.error(request, "Invalid username or Password")
                return render(request, 'admin_login.html', {'form':form_data})
        else:
            return render(request, 'admin_login.html', {'form':form_data})      
@method_decorator(adminOnly, name="dispatch")
class AdminLogOut(View):
    def get(self, request):
        logout(request)
        return redirect('admn')
@method_decorator(adminOnly, name="dispatch")
class AdmView(TemplateView):
    template_name = "admin.html"
@method_decorator(adminOnly, name="dispatch")
class AdmUsrView(TemplateView):
    template_name = "admin_U.html"
@method_decorator(adminOnly, name="dispatch")
class AdmProView(TemplateView):
    template_name = 'admin_P.html'
@method_decorator(adminOnly, name="dispatch")
class AdmMsgView(TemplateView):
    template_name = 'admin_M.html'
@method_decorator(adminOnly, name="dispatch")
class AdmFeedView(TemplateView):
    template_name = 'admin_F.html'
# Message Section
@adminOnly
def admDeleteMessage(self, *args, **kwargs):
    id =  kwargs.get("id")
    msg = MessageModel.objects.get(id=id)
    msg.delete()
    return redirect('admM')
# Feedback Section
@method_decorator(adminOnly, name="dispatch")
class AdmFeedEdit(View):
    def get(self, request, *args, **kwargs):
        id = kwargs.get("id")
        feed = FeedbackModel.objects.get(id=id)
        form = FeedbackForm(instance=feed)
        return render(request, "editfeed.html", {"form":form})
    def post(self, request, *args, **kwargs):
        id = kwargs.get("id")
        feed = FeedbackModel.objects.get(id=id)
        form_data = FeedbackForm(data=request.POST, instance=feed)
        if form_data.is_valid():
            form_data.save()
            return redirect('admF')
        else:
            messages.error(request,"something went wrong!")
            return render(request, "editfeed.html", {"form":form_data})
@adminOnly
def admFeedDelete(self, *args, **kwargs):
    id = kwargs.get("id")
    feed = FeedbackModel.objects.get(id=id)
    feed.delete()
    return redirect("admF")
@adminOnly
def admDeleteReport(self, *args, **kwargs):
    id = kwargs.get("id")
    feed = FeedbackModel.objects.get(id=id)
    Report.objects.filter(feedback=feed).delete()
    return redirect("admF")
# Staff Section
@method_decorator(adminOnly, name="dispatch")
class CreateStaff(View):
    def get(self, request):
        return render(request, "c_staff.html")
    def post(self, request):
        fname = request.POST.get("first_name")
        lname = request.POST.get("last_name")
        uname = request.POST.get("username")
        email = request.POST.get("email")
        pswd = request.POST.get("pssword")
        User.objects.create_user(first_name=fname, last_name=lname, username=uname, email=email, password=pswd, is_staff=True)
        return redirect('dash')
@adminOnly
def makeStaff(self, *args, **kwargs):
    id = kwargs.get('id')
    user = User.objects.get(id=id)
    user.is_staff=True
    user.save()
    return redirect('admU')
@adminOnly
def deleteStaff(self, *args, **kwargs):
    id = kwargs.get('id')
    user = User.objects.get(id=id)
    user.is_staff=False
    user.save()
    return redirect('admU')
@adminOnly
def activateUser(self, *args, **kwargs):
    id = kwargs.get('id')
    user = User.objects.get(id=id)
    user.is_active=True
    user.save()
    return redirect('admU')
@adminOnly
def deactivateUser(self, *args, **kwargs):
    id = kwargs.get('id')
    user = User.objects.get(id=id)
    user.is_active=False
    user.save()
    return redirect('admU')

main/staff/templates/addcloth.html
<!doctype html>
<html lang="en">
  <head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
      
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    <div class="container text-center">
        {% for i in messages %}
        <div class="bg-warning text-center">
            {{i}}
        </div>
        {% endfor %}
        <h3 class="text-primary text-center">Add New Cloth</h3>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <table class="table table-bordered">
                {{form.as_table}}
            </table>
            <div>
                <button class="btn btn-success btn-block">ADD</button>
            </div>
        </form>
    </div>

  </body>
</html>

main/staff/templates/admin.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- fontawesome -->
    <script src="https://kit.fontawesome.com/fb64fe6586.js" crossorigin="anonymous"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <style>
      @import url("https://fonts.googleapis.com/css2?family=Kaushan+Script&family=Noto+Serif+JP&family=Satisfy&display=swap");
      .navbar-brand{
            font-family: 'Satisfy', cursive;
        }
      .box:hover{
          margin-top: -5px;
          transition-duration: 0.5s;
      }
      
    </style>
  </head>
  <body>
      
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <div class="row m-0">
        <!-- left side -->
        <div class="col-md-3 border border-right p-0 vh-100" style="background-color: antiquewhite;">
          <a class="navbar-brand text-white bg-dark w-100 text-center mr-0" href="#"><i class="fa-brands fa-vimeo-v border border-warning p-2 mr-2 text-warning"></i>Vintage Cart</a>
          <div class="d-flex flex-column p-3">
            <div class="row text-secondary">
              <i class="fa-solid fa-house p-1"></i><h5 class="mr-2">DashBoard</h5>
            </div>
            <ul>
              <a href="{% url 'dash' %}"><li class="text-secondary">Home</li></a>            
              <a href="{% url 'admU' %}"><li class="text-secondary">Users</li></a>            
              <a href="{% url 'admP' %}"><li class="text-secondary">Products</li></a>            
              <a href="{% url 'admM' %}"><li class="text-secondary">Messages</li></a>            
              <a href="{% url 'admF' %}"><li class="text-secondary">Feedbacks</li></a>                   
            </ul>
          </div>
        </div>
        <!-- right side -->
        <div class="col p-0 col-md-9 pb-4">
            <div class="container-fluid p-2">
                <div class="row m-0 p-1 justify-content-between">
                    <h3>Analytics</h3>
                    <a href="{% url 'admLO' %}" class="btn btn-warning">LogOut</a>
                </div>
                <!-- profile -->
                <div class="row m-0 bg-primary p-3 rounded justify-content-between" style="height: 200px;">
                    <div class="row col-12 col-md-9 m-0">
                        <img src="{% static 'images/admin.jpeg' %}" alt="" width="80px" height="70px" class="rounded-circle">
                        <div class="col">
                            <h4>Hi Jasim</h4>
                            <p>Here is what’s happening with your projects today:</p>
                        </div>
                    </div>
                    <div class="col-md-3 d-none d-md-block">
                        <button class="btn btn-light font-weight-bold">What’s New</button>
                    </div>
                </div>
                <!-- end profile -->
                <!-- boxs -->
                <div class="p-3 d-flex justify-content-around flex-wrap position-relative mt-n5">
                    <div class="box px-1 p-2 border rounded bg-light  col-lg-3 mb-2" >
                        <div class=" d-flex justify-content-between align-items-center">
                            <h3>Users</h3>
                            <i class="fa-solid fa-user-group border p-3 rounded-circle bg-primary"></i>
                        </div>
                        <h2>{{users.count}}</h2>
                        <p class="m-0">more</p>
                    </div>
                    <div class="box px-1 p-2 border rounded bg-light col-lg-3 mb-2">
                        <div class="d-flex justify-content-between align-items-center">
                            <h3>Products</h3>
                            <i class="fa-solid fa-shirt border p-3 rounded-circle bg-primary"></i>
                        </div>
                        <h2>{{pros.count}}</h2>
                        <p class="m-0">more</p>
                    </div>
                    <div class="box px-1 p-2 border rounded bg-light col-lg-3 mb-2">
                        <div class="d-flex justify-content-between align-items-center">
                            <h3>Messages</h3>
                            <i class="fa-solid fa-comments border p-3 rounded-circle bg-primary"></i>
                        </div>
                        <h2>{{msgs.count}}</h2>
                        <p class="m-0">more</p>
                    </div>
                    <div class="box px-1 p-2 border rounded bg-light col-lg-3 mb-2">
                        <div class="d-flex justify-content-between align-items-center">
                            <h3>Feedbacks</h3>
                            <i class="fa-solid fa-list border p-3 rounded-circle bg-primary"></i>
                        </div>
                        <h2>{{feeds.count}}</h2>
                        <p class="m-0">more</p>
                    </div>
                </div>
                <!-- end boxs --> 
            </div>
        </div>
    </div>
  </body>

  
</html>

main/staff/templates/admin_F.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- fontawesome -->
    <script src="https://kit.fontawesome.com/fb64fe6586.js" crossorigin="anonymous"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <style>
      @import url("https://fonts.googleapis.com/css2?family=Kaushan+Script&family=Noto+Serif+JP&family=Satisfy&display=swap");
      .navbar-brand{
            font-family: 'Satisfy', cursive;
        }
      .box:hover{
          margin-top: -5px;
          transition-duration: 0.5s;
      }
      
    </style>
  </head>
  <body>
      
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <div class="row m-0">
        <!-- left side -->
        <div class="col-md-3 border border-right p-0 vh-100" style="background-color: antiquewhite;">
          <a class="navbar-brand text-white bg-dark w-100 text-center mr-0" href="#"><i class="fa-brands fa-vimeo-v border border-warning p-2 mr-2 text-warning"></i>Vintage Cart</a>
          <div class="d-flex flex-column p-3">
            <div class="row text-secondary">
              <i class="fa-solid fa-house p-1"></i><h5 class="mr-2">DashBoard</h5>
            </div>
            <ul>
              <a href="{% url 'dash' %}"><li class="text-secondary">Home</li></a>  
              <a href="{% url 'admU' %}"><li class="text-secondary">Users</li></a>            
              <a href="{% url 'admP' %}"><li class="text-secondary">Products</li></a>            
              <a href="{% url 'admM' %}"><li class="text-secondary">Messages</li></a>            
              <a href="{% url 'admF' %}"><li class="text-secondary">Feedbacks</li></a>                   
            </ul>
          </div>
        </div>
        <!-- right side -->
        <div class="col p-0 col-md-9 pb-4">
            <div class="container-fluid p-2">
                <div class="row m-0 p-1 justify-content-between">
                    <h3>Analytics</h3>
                    <a href="{% url 'admLO' %}" class="btn btn-warning">LogOut</a>
                </div>
                <!-- profile -->
                <div class="row m-0 bg-primary p-3 rounded justify-content-between" style="height: 200px;">
                    <div class="row col-12 col-md-9 m-0">
                        <img src="{% static 'images/admin.jpeg' %}" alt="" width="80px" height="70px" class="rounded-circle">
                        <div class="col">
                            <h4>Hi Jasim</h4>
                            <p>Here is what’s happening with your projects today:</p>
                        </div>
                    </div>
                    <div class="col-md-3 d-none d-md-block">
                        <button class="btn btn-light font-weight-bold">What’s New</button>
                    </div>
                </div>
                <!-- end profile -->
                <!-- boxs -->
                <div class="p-3 d-flex justify-content-around flex-wrap position-relative mt-n5">
                    <div class="box px-1 p-2 border rounded bg-light  col-lg-3 mb-2" >
                        <div class=" d-flex justify-content-between align-items-center">
                            <h3>Users</h3>
                            <i class="fa-solid fa-user-group border p-3 rounded-circle bg-primary"></i>
                        </div>
                        <h2>{{users.count}}</h2>
                        <p class="m-0">more</p>
                    </div>
                    <div class="box px-1 p-2 border rounded bg-light col-lg-3 mb-2">
                        <div class="d-flex justify-content-between align-items-center">
                            <h3>Products</h3>
                            <i class="fa-solid fa-shirt border p-3 rounded-circle bg-primary"></i>
                        </div>
                        <h2>{{pros.count}}</h2>
                        <p class="m-0">more</p>
                    </div>
                    <div class="box px-1 p-2 border rounded bg-light col-lg-3 mb-2">
                        <div class="d-flex justify-content-between align-items-center">
                            <h3>Messages</h3>
                            <i class="fa-solid fa-comments border p-3 rounded-circle bg-primary"></i>
                        </div>
                        <h2>{{msgs.count}}</h2>
                        <p class="m-0">more</p>
                    </div>
                    <div class="box px-1 p-2 border rounded bg-light col-lg-3 mb-2">
                        <div class="d-flex justify-content-between align-items-center">
                            <h3>Feedbacks</h3>
                            <i class="fa-solid fa-list border p-3 rounded-circle bg-primary"></i>
                        </div>
                        <h2>{{feeds.count}}</h2>
                        <p class="m-0">more</p>
                    </div>
                </div>
                <!-- end boxs -->

                <!-- feedback table -->
                <div class="row m-0" id="feedback">
                    <div class="col-12 border rounded p-0">
                        <table class="table table-hover">
                            <h5 class="p-2">Feedbacks</h5>
                            <thead class="bg-light">
                              <tr>
                                <th scope="col">SI No</th>
                                <th scope="col">User</th>
                                <th scope="col">Product</th>
                                <th scope="col">Title</th>
                                <th scope="col">Feedback</th>
                                <th scope="col">Likes</th>
                                <th scope="col">Reports</th>
                                <th scope="col">Actions</th>
                              </tr>
                            </thead>
                            <tbody>
                              {% for i in feeds %}
                              <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td scope="row">{{i.seller.username}}</td>
                                <td scope="row">{{i.pro.id}}</td>
                                <td scope="row">{{i.title}}</td>
                                <td scope="row">{{i.feedback}}</td>
                                <td scope="row">{{i.likes.count}}</td>
                                <td scope="row">{{i.report_set.count}}</td>
                                <td scope="row"><a href="{% url 'admfeededit' i.id %}" class="btn btn-success">Edit</a>
                                                <a href="{% url 'admdltfeed' i.id %}" class="btn btn-danger">Delete</a>
                                                <a href="" class="btn btn-primary">Reply</a>
                                                {% if i.report_set.count > 2 %}
                                                <a href="{% url 'd_reports' i.id %}" class="btn btn-secondary" title="UnLock"><i class="fa-solid fa-lock"></i></a></td> 
                                                {% else %}
                                                <i class="fa-solid fa-unlock"></i> 
                                                {% endif %}                                     
                              </tr>
                              {% endfor %}
                            </tbody>
                          </table>
                    </div>
                </div>
                <!-- end table -->
            </div>
        </div>
    </div>
  </body>

</html>

main/staff/templates/editfeed.html
<!doctype html>
<html lang="en">
  <head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
      
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    {% for i in messages %} 
    <div>
      {{i.messages}}
    </div>
    {% endfor %}
    <form action="" class="container" method="post">
      <h4>Updation Form</h4>
        {% csrf_token %}
        <div class="table">
             {{form.as_table}}
        </div>
        <button class="btn btn-success">Update</button>
    </form>

  </body>
</html>